## Anaconda
- 파이썬 통합 개발환경(IDE)
- jupyter notebook 지원
- https://www.anaconda.com/products/individual

## Jupyter notebook
- Windows Powershell (shift+우클릭) / 명령 프롬프트(cmd) / Mac OS X terminal
 실행
- jupyter notebook 입력
- H: 키보드 단축키 설명

## 데이터 처리 및 분석을 위한 파이썬 모듈

1. Numpy: 다차원 배열 생성 및 연산
2. Pandas: Dataframe 생성 및 조작
3. Scipy: 과학 및 공학 연산 --> 통계분석
4. Matplotlib: 시각화


In [2]:
#  모듈설치

### Windows 명령 프롬프트(cmd), Powershell 
#pip install numpy scipy pandas matplotlib --user
### Mac OS 터미널
#pip3 install numpy scipy pandas matplotlib
### Jupyter notebook
#!pip install numpy scipy pandas matplotlib


# Numpy
Numerical Python<br/><br/>
다차원 배열(multi-dimensional array)을 쉽고 빠르게 처리<br/>
숫자로 이루어진 Table형 데이터를 다룰 때 주로 사용<br/>
같은 종류의 data type을 원소로 함<br/>

https://wikidocs.net/14569


In [3]:
import numpy as np

In [4]:
tmp = [j for j in range(10)]
tmp1 = []
for i in range(len(tmp)):
    if i>3:
        tmp1.append(i)
tmp1

[4, 5, 6, 7, 8, 9]

In [5]:
xx = np.array(tmp)
list(xx[xx>3])

[4, 5, 6, 7, 8, 9]

In [6]:
xx = np.array(tmp)
print(xx, type(xx))
xx = xx.tolist()
print(xx, type(xx))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>


### 차원에 따라 데이터를 부르는 이름
- 1차원: vector<br/>
- 2차원: matrix<br/>
- 3차원: tensor


# Ndarray (N-dimensional Array) <b/>
- numpy를 통해 생성되는 n차원의 배열 객체
- 같은 data type만을 담을 수 있음
- 배열과 배열 간에 다양항 수학적 연산 가능


# List와 Array의 차이점
1. 선언 조건
- 리스트 : 숫자형, 문자열 등 모든 자료 타입 보존 가능
- 넘파이 배열 : 한 가지 자료형만 허용

2. 연산
- 리스트 : 덧셈 시 항목을 이어붙이는 concatenate 수행, 리스트 간의 다른 연산 허용X
- 넘파이 배열 : 덧셈 시 항목 간 덧셈을 수행 , 실수에 대한 사칙연산 과정 수행 가능 

3. 메소드
- 자료형의 종류가 다르기 지원하는 메소드의 종류가 다름 
(EX) 리스트에서는 mean, argmax, round 등 어레이 메소드 지원X

4. 연산 속도
- 같은 연산을 수행하는 경우 넘파이 배열이 연산 최적화가 더 잘되어 있음

## ndarray 생성 함수
- numpy.arange:np.arange([start,] stop[, step,], dtype=None)
- numpy.linspace: numpy.linspace(start, stop, [num=50, endpoint=True, retstep=False, dtype=None)])
- numpy.logspace: log scale

In [7]:
#array 함수의 인수에 리스트를 지정하여 배열 형성 
# numpy.array(object, [dtype=None, copy=True, order=None, subok=False, ndmin=0])
# 추가 키워드 인자 사용 가능

In [8]:
import numpy as np
a = [1,2,3,4,5]
print(a, type(a))
b= np.array(a)
print(b, type(b))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [9]:
b_list=b.tolist() # tolist()는 numpy의 ndarray를 list로 되돌리는 메소드
print(type(b_list))

<class 'list'>


In [10]:
c = [[1,2,3,4,5],[6,7,8,9,10]]
print(c, type(c))
d = np.array(c)
print(d, type(d))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]] <class 'list'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] <class 'numpy.ndarray'>


In [11]:
print(d)
print(d[1,2]) # 2번째 행, 3번째 열의 값 --> 8을 인덱싱

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
8


In [12]:
# size: 총 원소의 개수
# shape: 차원구조
# ndim : 차원 수
# dtype: 원소의 data type

a = "abcd"
b = list(a)
c = tuple(a)
d = dict((('a',1), ('b',2)))
e = set(a)

print(a, np.array(a).size, np.array(a).shape, np.array(a).ndim, np.array(a).dtype) # dtype에 유니코드 문자열인데 하나로 묶여 있으니 한번에 4바이트짜리 데이터를 갖고 있다
print(b, np.array(b).size, np.array(b).shape, np.array(b).ndim, np.array(b).dtype) # dtype의 <는 litte endian, U는 유니코드 문자열, 1은 문자열 하나당 1바이트를 사용한다는 것
print(c, np.array(c).size, np.array(c).shape, np.array(c).ndim, np.array(c).dtype) # 튜플을 인자로 넣어도 리스트와 동일하게 인식
print(d, np.array(d).size, np.array(d).shape, np.array(d).ndim, np.array(d).dtype) # 딕셔너리를 하나의 원소로 하는 ndarray 생성
print(e, np.array(e).size, np.array(e).shape, np.array(e).ndim, np.array(e).dtype) # 집합을 하나의 원소로 하는 ndarray 생성

abcd 1 () 0 <U4
['a', 'b', 'c', 'd'] 4 (4,) 1 <U1
('a', 'b', 'c', 'd') 4 (4,) 1 <U1
{'a': 1, 'b': 2} 1 () 0 object
{'b', 'd', 'c', 'a'} 1 () 0 object


In [13]:
a = np.arange(10)   # start는 default로 0, stop을 10으로 지정(미포함) --> 0~9까지
b = np.arange(1,10.) # 1부터 10(미포함)까지, .을 붙여서 dtype을 float으로 설정
c = np.arange(1,10,0.5) # step을 0.5로 설정
d = np.arange(1,10,3,dtype='float') # 시작, step을 보아 정수로 적힐 것이지만 dtype을 float으로 하여 강제로 실수로 선언

print(a)
print(b)
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[1. 4. 7.]


In [14]:
# linspace = linear + space --> 범위를 주고 일종의 분할을 수행하는 것, num의 개수를 원소의 개수로 맞춤

a = np.linspace(1,10) # num이 없으면 50이 default값이다
b = np.linspace(1,np.pi,num=5)                  
c = np.linspace(1,10, num=5, endpoint = False)  # stop 표시 X
d = np.linspace(1, 10., num=5, retstep=True)    # retstep : step 명시 여부 (step이 2.25였음이 옆에 표시되었다)
print(a)
print(b)
print(c)
print(d)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[1.         1.53539816 2.07079633 2.60619449 3.14159265]
[1.  2.8 4.6 6.4 8.2]
(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)


In [15]:
print(np.linspace(2, 4, 3)) # 2에서 4(포함)까지 3분할
print(np.logspace(2, 4, 3)) # log값이 2에서 4(포함)까지를 3분할 
print(np.log10(100),np.log10(1000),np.log10(10000))

[2. 3. 4.]
[  100.  1000. 10000.]
2.0 3.0 4.0


In [16]:
print(np.log2(4)) # log옆에 밑을 지정할 수 있다

2.0


In [17]:
a = np.ones((2,5)) #default dtype = float
b = np.zeros((2,5),dtype='int') #default dtype = float
c = np.full((2,3), 0.5)
d = np.eye(3, 5)    # (m, n) 크기의 0 행렬 + (m, m) 크기의 단위 행렬
e = np.identity(3)  # 3 by 3 단위행렬 (identity)

print(a)
print(b)
print(c)
print(d)
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b = a.T
print(b)
c = a.reshape(2,6)
print(c)
d = a.astype(float) # a의 원소들의 dtype을 float으로 변경한다
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [19]:
a = np.arange(9)
a.reshape(1, -1)    # reshape의 인자로 -1은 알아서 계산하는 것을 의미

b = a.reshape((1,1,9)) # 첫번째 차원에 1개, 두번째 차원에 1개, 세번째 차원에 9개 --> 총 3차원
c = a.reshape((1,9,1)) # 첫번째 차원에 1개(통으로), 두 번째 차원에 9개, 세번째 차원에 1개
d = a.reshape((9,1,1))

print(a)
print(b)
print(c)
print(d)

[0 1 2 3 4 5 6 7 8]
[[[0 1 2 3 4 5 6 7 8]]]
[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]]]
[[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]]


## ndarray의 연산

In [20]:
a = np.full((2,4),5)
a

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [21]:
# 두 연산 모두 ndarray이고 각 요소마다 해당 값을 더해준다
print(a + [2])
print(a + 2)

[[7 7 7 7]
 [7 7 7 7]]
[[7 7 7 7]
 [7 7 7 7]]


In [22]:
# 행 별로 맞추어 연산이 적용된다
print(a - [1,2,3,4])
print(a % [1,2,3,4])

[[4 3 2 1]
 [4 3 2 1]]
[[0 1 2 1]
 [0 1 2 1]]


In [23]:
a * ([2],[3]) # 첫 번째 행에 2, 두 번째 행에 3을 각각 곱해주는 꼴

array([[10, 10, 10, 10],
       [15, 15, 15, 15]])

In [24]:
print([a + 1], type([a + 1]))  #
print(a + 1, type(a + 1))
print(a / [a+1])    # 각 요소에 맞추어 5를 6으로 나눈 값이 들어간다
print(a / (a + 1))  # 각 요소에 맞추어 5를 6으로 나눈 값이 들어간다

[array([[6, 6, 6, 6],
       [6, 6, 6, 6]])] <class 'list'>
[[6 6 6 6]
 [6 6 6 6]] <class 'numpy.ndarray'>
[[[0.83333333 0.83333333 0.83333333 0.83333333]
  [0.83333333 0.83333333 0.83333333 0.83333333]]]
[[0.83333333 0.83333333 0.83333333 0.83333333]
 [0.83333333 0.83333333 0.83333333 0.83333333]]


In [25]:
x = a.tolist() + [1,2,3] # ndarray a를 list로 바꾸고 list연산을 하니 요소에 더하는 것이 아니라 뒤에 삽입되었다(concatenation)
print(x)
print(type(x))

[[5, 5, 5, 5], [5, 5, 5, 5], 1, 2, 3]
<class 'list'>


In [26]:
aa = np.arange(10).reshape(2,5)
bb = np.arange(10).reshape(5,2)

print(aa)
print(bb)

# 내적을 구하는 조건: 앞 ndarray의 열과 뒤 ndarray의 행이 일치해야 한다
print(aa @ bb) # 두 ndarray의 내적을 구한다
print(np.dot(aa,bb)) # 동일하게 내적을 구한다

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 60  70]
 [160 195]]
[[ 60  70]
 [160 195]]


## ndarray의 인덱싱 & 슬라이싱

In [27]:
a = np.arange(1,8) # [ 1, 2, 3, 4, 5, 6, 7]
print(a[1:6])      # start 포함, stop 미포함
print(a[1:6:2])    # step 2
print(a[6:1:-1])

[2 3 4 5 6]
[2 4 6]
[7 6 5 4 3]


In [28]:
#변수[행 슬라이싱, 열 슬라이싱]
a=np.arange(1,13).reshape(3,4)
print(a)
print(a[0:2, 1:3]) # 행에서는 0~1(2미포함), 열에서는 1~2(3미포함)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


## Numpy.Random 함수

1. numpy.random.rand(shape) : [0, 1)에서 무작위 숫자 shape에 맞춰 생성

2. numpy.random.randn(shape) : 표준정규분포에서 무작위 숫자 shape에 맞춰 생성

3. numpy.random.randint([low], high, [size/shape]) : [low, high)에서 무작위 정수 size개, default low=0

In [29]:
print(np.random.rand(5))        # 0부터 1까지 5개로 만듦
print(np.random.rand(2, 3))     # 0부터 1까지 2행 3열의 총 6개 원소의 난수

[0.40373848 0.84664513 0.24885677 0.25394887 0.58357848]
[[0.03288117 0.43211689 0.76810746]
 [0.04123688 0.78362676 0.74074968]]


In [30]:
# rand함수와 동일하나 표준 정규분포에서 생성한다는 점만 차이가 있음
print(np.random.randn(5))
print(np.random.randn(2, 3))

[-0.42118352 -0.8608132   2.07991819  0.53002122 -0.01615445]
[[-1.32852468  1.80873431  0.83966186]
 [-0.15843662  0.38725913 -0.39706101]]


In [31]:
print(np.random.randint(2, size=5))         # [0, 2)에서 5개 난수
print(np.random.randint(2, 4, size=5))      # [2, 4)에서 5개 난수
print(np.random.randint(1, 5, size=(2,3)))  # [1, 5)에서 (2, 3)의 shape으로 난수

#print(np.random.randint(2, 4, size=5, dtype='float64')) # dtype으로 float을 줄 수 없다(int형만 가능)

[1 0 1 0 0]
[2 3 3 3 3]
[[2 4 3]
 [1 2 3]]


## Random.seed의 역할

seed : 시드는 난수 생성 알고리즘의 초기값을 결정, 동일한 시드로 시드를 설정하면 항상 동일한 순서로 난수가 생성 --> 무작위성을 시뮬레이션하거나 재현 가능한 결과를 얻기 위해    
shuffle : 특정 패턴을 가지고 조합을 하는 함수 

In [32]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.random.seed(0); np.random.shuffle(x)
x

array([2, 8, 4, 9, 1, 6, 7, 3, 0, 5])

In [34]:
np.random.seed(0); np.random.shuffle(x)
x

array([4, 0, 1, 5, 8, 7, 3, 9, 2, 6])

In [35]:
np.random.seed(0); np.random.shuffle(x)
x

array([1, 2, 8, 6, 0, 3, 9, 5, 4, 7])

In [36]:
np.random.seed(0); np.random.shuffle(x)
x

array([8, 4, 0, 7, 2, 9, 5, 6, 1, 3])

In [37]:
np.random.seed(0); np.random.shuffle(x)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.random.seed(0); np.random.shuffle(x)
x
# shuffle 할 때마다 2칸씩 좌측으로 앞당겨지는 것을 확인할 수 있다.
# 10개의 원소이기 때문에 shuffle 5번 돌면 동일한 값이 출력되는 것을 확인 가능

array([2, 8, 4, 9, 1, 6, 7, 3, 0, 5])

seed가 같으면, random 함수로 난수를 생성할 때 동일한 난수가 생성   
seed가 다르면, 동일한 난수가 생성되지 않는다

In [39]:
np.random.seed(0); np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [40]:
np.random.seed(0); np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [41]:
np.random.seed(5); np.random.rand(5)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])

## Numpy 연산

In [42]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.cumsum(x) # 누적합

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [44]:
print(np.cumprod(x))        # 누적곱 (0이 맨 앞이라 모두 0)
print(np.cumprod(x[1:]))    # 맨 앞의 0을 빼고 계산한 누적 곱

[0 0 0 0 0 0 0 0 0 0]
[     1      2      6     24    120    720   5040  40320 362880]


In [45]:
np.diff(np.cumsum(x))   # diff : 좌측 숫자와의 차이 --> 누적합에서 diff를 적용한 상황

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Numpy 1차원 변환 

In [46]:
a1=np.arange(1,5).reshape(2,2)
a2=a1.ravel()
a3=a1.flatten()    # 원본(a1) 값을 바꾸지 않는다
a4=a1.reshape(-1)  # reshape에 '-1' 하나만 넣어서 일차원으로 펴는 방식
print(a1,'\n')
print(a2,'\n')
print(a3,'\n')
print(a4)

[[1 2]
 [3 4]] 

[1 2 3 4] 

[1 2 3 4] 

[1 2 3 4]


In [47]:
a1[0][0] = 0   # mutable을 수정
print(a1,'\n') # 원본이 수정되어 반영됨
print(a2,'\n') # flatten은 원본 값의 변화에 영향을 받지 않음
print(a3,'\n') # 원본이 수정되어 반영됨
print(a4)

[[0 2]
 [3 4]] 

[0 2 3 4] 

[1 2 3 4] 

[0 2 3 4]


## Numpy 합치기

In [48]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

print(a1, '\n')
print(a2, '\n')

print(np.concatenate((a1,a2), axis=0), '\n') # axis=0으로 행 방향으로(아래 방향) concat
print(np.concatenate((a1,a2), axis=1))       # axis=1로 열 방향(우측 방향)으로 concat

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]]


## Numpy 반복 

- axis=0 : row끼리의 연산 --> 오른쪽 방향으로 연산

- axis=1 : column끼리의 연산 --> 아래쪽 방향으로 연산

- repeat : 해당 원소를 바로 반복한다

- tile : 해당 부분을 마치 타일처럼 블록 단위로 반복한다

In [55]:
a1=np.array([[1,2],[3,4]])
print(a1, '\n')
print(a1.repeat(2), '\n') # axis 옵션이 없으면 1차원으로 분리해서 반복
print(a1.repeat(2, axis=0), '\n') # axis=0으로 행별로 반복
print(a1.repeat(2, axis=1), '\n') # axis=1로 열별로 반복

[[1 2]
 [3 4]] 

[1 1 2 2 3 3 4 4] 

[[1 2]
 [1 2]
 [3 4]
 [3 4]] 

[[1 1 2 2]
 [3 3 4 4]] 



In [63]:
# repeat은 각 원소를 바로 반복한다면, tile은 해당 부분을 타일처럼 한꺼번에 반복한다

a1=np.array([[1,2],[3,4]])

print(np.tile(a1,2),'\n')
print(np.tile(a1,(2,3)))

[[1 2 1 2]
 [3 4 3 4]] 

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [61]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
print(np.append(a1, a2))    # 모든 원소를 합쳐서 1차원으로 출력

[1 2 3 4 5 6 7 8]


## Numpy 정렬 

In [66]:
a=np.array([[2,1,6],[0,7,4],[5,3,2]])
print(a, '\n\n')
print(np.sort(a, axis=1), '\n')             # 열 단위로 오름차순 정렬
print(np.sort(a, axis=1)[::,::-1], '\n')    # 열 단위로 내림차순 정렬 --> 오름차순 정렬 다음에 [::-1]로 역순 만들기
print(np.sort(a, axis=0), '\n')             # 행 끼리 비교해서 오름차순
print(np.sort(a, axis=0)[::-1])             # 행 끼리 비교해서 내림차순

[[2 1 6]
 [0 7 4]
 [5 3 2]] 


[[1 2 6]
 [0 4 7]
 [2 3 5]] 

[[6 2 1]
 [7 4 0]
 [5 3 2]] 

[[0 1 2]
 [2 3 4]
 [5 7 6]] 

[[5 7 6]
 [2 3 4]
 [0 1 2]]


In [67]:
# np.sort(a)로 정렬된 출력값의 index
np.argsort(a)

array([[1, 0, 2],
       [0, 2, 1],
       [2, 1, 0]], dtype=int64)

In [68]:
a.argsort()

array([[1, 0, 2],
       [0, 2, 1],
       [2, 1, 0]], dtype=int64)

In [75]:
print(np.amin(a), a.min())    # 최솟값(amin은 min과 거의 유사)
print(np.amax(a), a.max())    # 최댓값(amax는 max와 거의 유사)
print(np.argmin(a), a.argmin())    # 최솟값 index
print(np.argmax(a), a.argmax())    # 최댓값 index

0 0
7 7
3 3
4 4


In [76]:
# 연립방정식 해 구하기

# x+2y=5 2x+3y=8
A = np.linalg.inv(np.array([[1,2],[2,3]]))    # np.linalg.inv: 역행렬
B = np.array([5,8])
C = np.dot(A,B); C    # np.dot : 행렬의 곱(내적)

array([1., 2.])

In [77]:
a = np.random.rand(3,2)
print(a)

[[0.61174386 0.76590786]
 [0.51841799 0.2968005 ]
 [0.18772123 0.08074127]]


In [78]:
np.savetxt('out.txt', a, fmt='%.4f', delimiter='\t') # fmt: 출력 형태 / delimiter: 데이터를 구분하는 것을 설정(\t는 tab키)
np.loadtxt('out.txt', dtype='float', delimiter='\t')

array([[0.6117, 0.7659],
       [0.5184, 0.2968],
       [0.1877, 0.0807]])

## Numpy의 where 

- np.where(condition, true일때, false일때) 

- 1차원: 직관적으로 조건에 맞는 '인덱스'를 반환

- 2차원: [행의 index], [열의 index]를 반환 

In [94]:
a = np.arange(5, 15) # start ~ stop(불포함), step=1
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [97]:
np.where(a > 10) # 10보다 큰 것들의 index 값들을 반환

(array([6, 7, 8, 9], dtype=int64),)

In [98]:
np.where(a % 3 == 0) # 1번(6), 4번(9), 7번(12)을 반환

(array([1, 4, 7], dtype=int64),)

In [90]:
a = np.array([[15, 8, 12], [11, 7, 3]])
np.where(a > 10) # (array([0, 0, 1]), array([0, 2, 0]))

# (0, 0)인 15,  (0, 2)인 12, (1, 0)인 11을 의미하는 인덱스

(array([0, 0, 1], dtype=int64), array([0, 2, 0], dtype=int64))

In [99]:
a = np.array([[15, 8, 12], [11, 7, 3]])
np.where(a > 10, a, 10)  # a>10일때는 a 그대로, a>10이 아닐때는 10으로

array([[15, 10, 12],
       [11, 10, 10]])

In [100]:
b = np.array([[0, -1, 2], [-2, -1, -3]])
np.where(a > 10, a * 2, b) # a가 10보다 크면 a의 해당 값*2, 아니면 b의 값을 넣는다

array([[30, -1, 24],
       [22, -1, -3]])

## Bincount : 양의 정수 객체의 정수값에 대한 빈도수 계산 

In [103]:
x=np.random.randint(1, 10, 15) # 1부터 9(10불포함) 사이의 난수 15개
x

array([6, 8, 1, 7, 1, 6, 3, 9, 7, 9, 1, 6, 3, 1, 8])

In [104]:
# 0부터 최대값 범위의 정수값에 대한 빈도수를 반환
np.bincount(x) # 0은 0번, 1은 4번, 2는 0번, 3은 2번 등등등

array([0, 4, 0, 2, 0, 0, 3, 2, 2, 2], dtype=int64)